### ISSUE TITLE
Cannot support Python 2.x

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-python#25]
https://pypi.org/project/observable/

> **Note:** We are Python 3 only! Only Python Versions >= 3.5 are supported. Use [v0.3.2](https://pypi.org/project/observable/0.3.2/) for older Python Versions.

This SDK specifies `observable>=0.3.1` in requirements. I think we need to change it to `observable==0.3.2`

**Comment by byrnereese** [comment]
I have an aching suspicion that the following error stems from this reported issue:

```
Traceback (most recent call last):
  File "sms.py", line 1, in <module>
    from ringcentral import SDK
  File "/usr/local/lib/python2.7/site-packages/ringcentral/__init__.py", line 4, in <module>
    from .sdk import SDK
  File "/usr/local/lib/python2.7/site-packages/ringcentral/sdk.py", line 4, in <module>
    from .platform import Platform
  File "/usr/local/lib/python2.7/site-packages/ringcentral/platform/__init__.py", line 5, in <module>
    from .platform import Platform
  File "/usr/local/lib/python2.7/site-packages/ringcentral/platform/platform.py", line 5, in <module>
    from observable import Observable
  File "/usr/local/lib/python2.7/site-packages/observable/__init__.py", line 7, in <module>
    from .core import Observable, EventNotFound, HandlerNotFound
  File "/usr/local/lib/python2.7/site-packages/observable/core.py", line 15
    def __init__(self, event: str, handler: T.Callable) -> None:
                            ^
SyntaxError: invalid syntax
```

**Comment by yanminhui** [comment]
> https://pypi.org/project/observable/
> 
> > **Note:** We are Python 3 only! Only Python Versions >= 3.5 are supported. Use [v0.3.2](https://pypi.org/project/observable/0.3.2/) for older Python Versions.
> 
> This SDK specifies `observable>=0.3.1` in requirements. I think we need to change it to `observable==0.3.2`

Function annotation syntax has been a Python feature since version 3.0. See [PEP 3107](https://www.python.org/dev/peps/pep-3107/)

It may be another way to fix this issue by copy the source files to this SDK's source directories, then check function's type of parameter by `isinstanceof`.

**Comment by kirill-konshin** [comment]
Fixed
