### ISSUE TITLE
Installation issue on Windows 10

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-python#5]
Windows 10 64-bit, PowerShell.

```
pip install ringcentral
Collecting ringcentral
  Using cached ringcentral-0.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\tyler\appdata\local\temp\pip-build-geexp8\ringcentral\setup.py", line 3, in <module>
        VERSION = __import__("ringcentral").VERSION
      File "ringcentral\__init__.py", line 4, in <module>
        from .sdk import SDK
      File "ringcentral\sdk.py", line 6, in <module>
        from .mocks import Registry
      File "ringcentral\mocks\__init__.py", line 4, in <module>
        from .client import Client
      File "ringcentral\mocks\client.py", line 5, in <module>
        import requests
    ImportError: No module named requests

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\tyler\appdata\local\temp\pip-build-geexp8\ringcentral\
```

I checked `setup.py` and I did see

```
    install_requires=[
        'pubnub>=3.7.0',
        'requests>=2.7.0'
    ],
```

I have no idea what's the root cause.

**Comment by MichaelDwyer** [comment]
Hi tylerlong,

I had the same issue on Windows 7.  I first attempted to install each pip package, and if installed, then I updated it.

Try (outside of Python on command prompt):
```
python -m pip install pubnub
python -m pip install requests
python -m pip install pubnub --update
python -m pip install requests  --update
python -m pip install ringcentral
```

That cleared up the issue for me.  I hope this is helpful for you and others.  

Cheers.
Michael

**Comment by kirill-konshin** [comment]
Is this still valid?

**Comment by tylerlong** [comment]
I haven't been using my windows machine for very long time and I don't have new feedbacks.

If other users encounter this, he/she could always install `requests` manually by `pip install requests` as a workaround.

Feel free to close it.
